# SPDX-FileCopyrightText: The Ferrocene Developers
# SPDX-License-Identifier: MIT OR Apache-2.0

---

name: "Use Ferrocene"
description: "Use Ferrocene instead of Rustup"
inputs:
  token:
    description: The CriticalUp token to use (use a GHA Secret)
    required: true
  uninstall-rust:
    description: If Rust should be uninstalled as well, ensuring only Ferrocene is used.
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Remove Rust
      if: ${{ inputs.uninstall-rust == 'true' }}
      shell: bash
      run: |
        rm -rf ~/.rustup
        rm -rf ~/.cargo
    - name: Install Ferrocene
      shell: bash
      run: |
        curl --proto '=https' --tlsv1.2 -LsSf https://github.com/ferrocene/criticalup/releases/latest/download/criticalup-installer.sh | sh
        criticalup auth set ${{ inputs.token }}
        criticalup install

    - name: Add Ferrocene to path
      shell: bash
      if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
      run: |
        ${{ runner.os == 'Linux' && 'echo "Adding to bash path: $HOME/.local/share/criticalup/bin"' || '' }}
        ${{ runner.os == 'Linux' && 'echo "$HOME/.local/share/criticalup/bin" >> $GITHUB_PATH' || '' }}
        
        ${{ runner.os == 'Windows' && 'echo "Adding to bash path: $HOME/AppData/Roaming/criticalup/bin"' || '' }}
        ${{ runner.os == 'Windows' && 'echo "$HOME/AppData/Roaming/criticalup/bin" >> $GITHUB_PATH' || '' }}
        
        ${{ runner.os == 'macOS' && 'echo "Adding to bash path: $HOME/Library/Application Support/criticalup/bin"' || '' }}
        ${{ runner.os == 'macOS' && 'echo "$HOME/Library/Application Support/criticalup/bin" >> $GITHUB_PATH' || '' }}

    - name: Add Ferrocene to path
      shell: pwsh
      if: ${{ runner.os == 'Windws' }}
      run: |
        echo "Adding to Powershell path: $HOME/AppData/Roaming/criticalup/bin"
        echo "$HOME/AppData/Roaming/criticalup/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append