# SPDX-FileCopyrightText: The Ferrocene Developers
# SPDX-License-Identifier: MIT OR Apache-2.0

[workspace]
members = ["cargo:."]

# Config for 'cargo dist'
[dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.23.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell", "msi"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Which actions to run on pull requests
pr-run-mode = "upload"
# Whether to install an updater program
install-updater = false
ssldotcom-windows-sign = "prod"
# Whether builds should try to be cached in CI
cache-builds = false
# Path that installers should place binaries in
install-path = "CARGO_HOME"

[dist.dependencies.apt]
gcc-aarch64-linux-gnu = "*"
binutils-aarch64-linux-gnu = "*"
"g++-aarch64-linux-gnu" = "*"
libc6-dev-arm64-cross = "*"
