# SPDX-FileCopyrightText: The Ferrocene Developers
# SPDX-License-Identifier: MIT OR Apache-2.0

[build]
rustflags = ["--cfg", "hyper_unstable_tracing"]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
