# SPDX-FileCopyrightText: The Ferrocene Developers
# SPDX-License-Identifier: MIT OR Apache-2.0

---

name: "Install criticalup"
description: "Configure repo for criticalup use"
inputs:
  token:
    description: The CriticalUp token to use (use a GHA Secret)
    required: true
  path:
    description: The installation path
    required: true
  matrix:
    description: Platforms to run on
    required: true
  runner:
    description: OS to run
    required: true

runs:
  using: composite
  steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: criticalup-${{ matrix.target }}.${{ runner.os == 'Windows' && 'zip' || 'tar.xz' }}
        path: ${{ path }}

    - name: Unpack archive
      shell: bash
      if: ${{ runner.os == 'Windows' }}
      working-directory: ${{ path }}
      run: |
        powershell -c "Expand-Archive criticalup-${{ matrix.target }}.zip"
        mv criticalup-${{ matrix.target }}/criticalup.exe criticalup.exe

    - name: Unpack archive and make executable
      shell: bash
      if: ${{ runner.os != 'Windows' }}
      working-directory: ${{ path }}
      run: |
        tar xvf criticalup-${{ matrix.target }}.tar.xz
        mv criticalup-${{ matrix.target }}/criticalup criticalup
        chmod +x ./criticalup

    - name: Auth Criticalup
      shell: bash
      working-directory: ${{ path }}
      run: ./criticalup auth set $CRITICALUP_TOKEN

    - name: Install toolchain
      shell: bash
      working-directory: ${{ path }}
      run: |
        ./criticalup install

    - name: Create toolchain link
      shell: bash
      working-directory: ${{ path }}
      run: |
        ./criticalup link create

    - name: Run `criticalup run` test workflow
      shell: bash
      working-directory: ${{ path }}
      run: |
        # We cannot run cargo init, it is an existing project
        ./criticalup run -- cargo build
        ./criticalup run -- cargo run
        ./criticalup which rustc

    # Windows allows the `.exe` or not at the users option.
    - name: Run Windows exclusive commands
      shell: bash
      if: ${{ runner.os == 'Windows' }}
      working-directory: ${{ path }}
      run: |
          ./criticalup.exe run -- cargo --version
          ./criticalup run -- cargo.exe --version
          ./criticalup.exe run -- cargo.exe --version

    - name: Run `cargo +ferrocene` test workflow
      shell: bash
      working-directory: ${{ path }}
      run: |
        cargo +ferrocene build
        cargo +ferrocene run --bin criticalup help

    - name: Remove toolchain link
      shell: bash
      working-directory: ${{ path }}
      run: |
        ./criticalup link remove

    - name: Run test cleanup workflow
      shell: bash
      working-directory: ${{ path }}
      run: |
        ./criticalup remove
        ./criticalup clean
