# SPDX-FileCopyrightText: The Ferrocene Developers
# SPDX-License-Identifier: MIT OR Apache-2.0

---

name: CI
on:
  push:
    branches: [staging, trying]
  pull_request: {}

permissions:
  # Allow write access to the source code to enable GitHub Pages publishing.
  contents: read

jobs:
  build:
    strategy:
      matrix:
        include:
          - runner: macos-latest
            target: aarch64-apple-darwin
          - runner: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
            glibc: "2.32"
          - runner: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
            glibc: "2.32"
          - runner: windows-latest
            target: x86_64-pc-windows-msvc
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      runner: ${{ matrix.runner }}
      target: ${{ matrix.target }}
      glibc: ${{ matrix.glibc }}
      release: false

  integration-test:
    name: Test CriticalUp on GHA Runners
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: macos-latest
            target: aarch64-apple-darwin
          - runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - runner: windows-latest
            target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.runner }}
    env:
      CRITICALUP_TOKEN: ${{ secrets.CRITICALUP_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: "Define toolchain"
        shell: bash # Powershell does not do heredocs
        run: |
          mkdir -p crab-boil
          cd crab-boil
          cat <<- EOF > criticalup.toml
            manifest-version = 1

            [products.ferrocene]
            release = "stable-24.11.0"
            packages = [
                "cargo-\${rustc-host}",
                "rustc-\${rustc-host}",
                "rust-std-\${rustc-host}",
            ]
          EOF

      - uses: actions/download-artifact@v4
        with:
          name: criticalup-${{ matrix.target }}.${{ runner.os == 'Windows' && 'zip' || 'tar.xz' }}
          path: crab-boil

      - name: Unpack archive
        if: ${{ runner.os == 'Windows' }}
        working-directory: crab-boil
        run: |
          powershell -c "Expand-Archive criticalup-${{ matrix.target }}.zip"
          mv criticalup-${{ matrix.target }}/criticalup.exe criticalup.exe

      - name: Unpack archive and make executable
        if: ${{ runner.os != 'Windows' }}
        working-directory: crab-boil
        run: |
          tar xvf criticalup-${{ matrix.target }}.tar.xz
          mv criticalup-${{ matrix.target }}/criticalup criticalup
          chmod +x ./criticalup

      - name: Auth Criticalup
        working-directory: crab-boil
        run: ./criticalup auth set $CRITICALUP_TOKEN


      - name: Install toolchain
        working-directory: crab-boil
        run: |
          ./criticalup install

      - name: Run test workflow
        working-directory: crab-boil
        run: |
          ./criticalup run -- cargo init
          
          ./criticalup run -- cargo build
          
          ./criticalup run -- cargo run

          ./criticalup which rustc

      # Windows allows the `.exe` or not, at the users option.
      - name: Run Windows exclusive commands
        if: ${{ runner.os == 'Windows' }}
        working-directory: crab-boil
        run: |
            ./criticalup.exe run -- cargo --version
            ./criticalup run -- cargo.exe --version
            ./criticalup.exe run -- cargo.exe --version

      - name: Run test cleanup workflow
        working-directory: crab-boil
        run: |
          ./criticalup remove

          ./criticalup clean


  license:
    name: Check licenses
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install REUSE
        run: pipx install reuse

      - name: Check compliance with REUSE
        run: reuse lint

  docs:
    name: Build documentation
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Build documentation and check links
        working-directory: ./docs
        run: ./make.py --check-links

      - name: Verify Python code formatting
        working-directory: ./docs
        run: uvx black . --check --diff --color

      - name: Lint Python code with flake8
        working-directory: ./docs
        run: uvx flake8 . --exclude .venv

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html

  deploy-docs:
    if: github.event_name == 'push' && github.ref == 'refs/heads/staging'
    needs:
      - docs
    environment:
      name: github-pages
      url: ${{ steps.github-pages.outputs.page_url }}
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: github-pages

  build-finished:
    name: CI build successful
    runs-on: ubuntu-latest
    if: success()
    needs:
      - build
      - integration-test
      - docs
      - deploy-docs
    steps:
      - name: Mark the build as successful
        run: exit 0
