# SPDX-FileCopyrightText: The Ferrocene Developers
# SPDX-License-Identifier: MIT OR Apache-2.0

---

name: Package

on:
  workflow_call:
    inputs:
      glibc:
        type: string
        description: (Linux only) The glibc version to use
    outputs:
      run-id:
        description: The id of the workflow run
        value: ${{ github.run_id }}
      msi-id:
        description: The artifact msi id
        value: ${{ jobs.msi.outputs.msi-id }}

defaults:
  run:
    shell: bash

jobs:
  msi:
    runs-on: windows-latest
    outputs:
      msi-id: ${{ steps.msi.outputs.artifact-id }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/use-ferrocene/
        with:
          token: ${{ secrets.CRITICALUP_TOKEN }}
          uninstall-rust: true  

      - name: Install WiX
        run: |
          mkdir -p ~/msi
          cd ~/msi
          curl -L -o wix.zip https://github.com/wixtoolset/wix3/releases/download/wix3141rtm/wix314-binaries.zip
          unzip wix.zip

      - name: Copy Signtool into msi folder
        run:
          cp "/c/Program Files (x86)/Windows Kits/10/bin/10.0.22000.0/x64/signtool.exe" ~/msi/signtool.exe

      - name: Install cargo-binstall
        run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
      
      - name: Install cargo-wix
        run: cargo install --git https://github.com/volks73/cargo-wix --rev 590bc2b602758086e8cdbf62503262780a0b73a4 --locked cargo-wix

      - name: Run cargo-wix
        run: cargo wix --package criticalup --bin-path ~/msi

      - name: Sign with cargo-wix
        run: cargo wix sign Cargo.toml --bin-path ~/msi -p criticalup

      - name: Upload msi
        id: msi
        uses: actions/upload-artifact@v4
        with:
          name: criticalup-signed-msi
          path: target/wix/criticalup-*
          retention-days: 7

      